# Generated by Django 2.0.1 on 2018-01-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('con', 'Control'), ('mix', 'Mixed'), ('mob', 'Mobility'), ('off', 'Offense'), ('sur', 'Survival')], max_length=3)),
                ('picture', models.ImageField(upload_to='D:\\py_battlerite\\battlerite\\static\\media')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cards', models.ManyToManyField(to='guides.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('m', 'Melee'), ('r', 'Range'), ('s', 'Support')], max_length=1)),
                ('lore', models.TextField()),
                ('cut_lore', models.CharField(max_length=200)),
                ('portrait', models.ImageField(upload_to='D:\\py_battlerite\\battlerite\\static\\media')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Hero'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Hero'),
        ),
    ]
