# Generated by Django 2.0.1 on 2018-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(),
        ),
    ]
