# Generated by Django 2.0.1 on 2018-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.CharField(max_length=240),
        ),
    ]
