# Generated by Django 2.0.1 on 2018-01-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20180119_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
