# Generated by Django 2.0.1 on 2018-01-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='description',
            new_name='desc',
        ),
    ]
